/**
 * What the email to the banker actually says.
 *
 * Source of truth: ADR-039.
 *
 * WHY THIS IS DETERMINISTIC AND NOT GENERATED BY A MODEL. Every word below is
 * computed from facts AOS already holds. That is a deliberate refusal, and the
 * reasons are the same four ADR-016 gives for not letting a model answer
 * eligibility:
 *
 *   It is auditable. The submission record can state the subject that went out
 *   and a reader can reproduce it exactly. A generated sentence can only be
 *   quoted, never re-derived.
 *
 *   It is private. Customer names, loan amounts and document lists are not
 *   sent to a third party in order to write "please find attached".
 *
 *   It is consistent. A banker who receives forty files a month from Amaze
 *   should be able to recognise one at a glance. Forty differently-phrased
 *   covering notes are forty things to read.
 *
 *   It costs nothing and cannot fail. There is no key to expire, no quota to
 *   exhaust, and no outage that stops a file going to a bank.
 *
 * WHY IT STILL HAS TO SOUND LIKE A PERSON. A banker who receives an obviously
 * automated notification treats it as one — which means it is skimmed, and the
 * query comes back anyway. The office's own covering note is three sentences,
 * and this writes those three sentences.
 *
 * WHAT IT DELIBERATELY DOES NOT DO. It does not invent an honorific. AOS holds
 * no gender for anybody, and "Mr." derived from a name is a guess that is
 * wrong often enough to be worth avoiding in a letter to a bank — so the
 * customer is named plainly, which is also how the case screen names them.
 */

import { describeGroups, groupOf, groupProse, joinWithAmpersand, type AttachmentBatch } from "./batching.js";
import type { CandidateDocument } from "./attachments.js";

/** Who the email comes from. Configuration, never hard-coded (ADR-039). */
export interface EmailSender {
  /** "Amaze Loans" — the display name on the From line. */
  readonly name: string;
  /** The authenticated mailbox. Never a spoofed address. */
  readonly address: string;
}

/** Everything about the case the wording draws on. */
export interface SubmissionContext {
  /** The primary applicant, as the case screen names them. */
  readonly customerName: string;
  /** The customer-facing lending product name — "Machinery and Equipment
   * Loan". AOS's own name for it (Milestone 7.1, ADR-033); this module does
   * not invent a second loan vocabulary. */
  readonly loanTypeName: string;
  /** The bank and branch, from the submission snapshot. Used in the body's
   * reference line, never re-read from live master data (ADR-036). */
  readonly counterparty?: string | undefined;
  readonly caseNumber?: string | undefined;
}

/** The banker this email is addressed to. */
export interface BankerRecipient {
  readonly email: string;
  readonly name?: string | undefined;
}

// ---------------------------------------------------------------------------
// Subject.
// ---------------------------------------------------------------------------

/**
 * CUSTOMER NAME - LOAN TYPE - DOCUMENT DESCRIPTION, with "(1/3)" appended when
 * the submission runs to more than one email.
 *
 * The description says what is in THIS email — "GST Documents (1/2)" then "ITR
 * Documents (2/2)" — rather than the same generic word twice. A banker filing
 * two identical subjects has to open both to find out which is which.
 *
 * The separator is a spaced hyphen because that is what the office writes.
 * Nothing parses this string; it is read by a person.
 */
export function composeSubject(
  context: SubmissionContext,
  batch: AttachmentBatch,
  batchCount: number,
): string {
  const description = describeGroups(batch.groups);
  const base = `${context.customerName} - ${context.loanTypeName} - ${description}`;
  return batchCount > 1 ? `${base} (${batch.sequence}/${batchCount})` : base;
}

// ---------------------------------------------------------------------------
// Greeting.
// ---------------------------------------------------------------------------

/**
 * "Dear Karthik," when a name is known, "Dear Sir / Madam," when it is not.
 *
 * Half the addresses a file goes to are desks — `homeloans.cbe@bank.com` has
 * no first name and deriving one from the local part would produce "Dear
 * Homeloans". A professional generic greeting is correct there, and the
 * milestone says so explicitly.
 */
export function composeGreeting(recipient: BankerRecipient): string {
  const first = firstName(recipient.name);
  return first === undefined ? "Dear Sir / Madam," : `Dear ${first},`;
}

/**
 * The given name out of a recorded name, skipping initials.
 *
 * "Karthik V" → "Karthik". "S. Karthik" → "Karthik". "V K" → "V K", because
 * two initials and nothing else is not a first name and truncating it to "V"
 * would read as a mistake.
 */
function firstName(name: string | undefined): string | undefined {
  const trimmed = name?.trim();
  if (trimmed === undefined || trimmed === "") return undefined;

  const tokens = trimmed.split(/\s+/);
  const spelled = tokens.filter((token) => token.replace(/\./g, "").length > 2);
  const chosen = spelled[0] ?? undefined;
  return chosen ?? trimmed;
}

// ---------------------------------------------------------------------------
// Body.
// ---------------------------------------------------------------------------

const NUMBER_WORDS = [
  "zero",
  "one",
  "two",
  "three",
  "four",
  "five",
  "six",
  "seven",
  "eight",
  "nine",
  "ten",
  "eleven",
  "twelve",
] as const;

/** "three" up to twelve, "17" after that. How a person writes a count. */
export function numberWord(count: number): string {
  return NUMBER_WORDS[count] ?? String(count);
}

/**
 * What this email contains, as a phrase: "the GST documents and three years of
 * ITR documents".
 *
 * A group whose documents span more than one financial year is counted, because
 * "three years of ITR documents" is the thing a banker is actually checking for
 * and "the ITR documents" leaves them counting attachments.
 */
export function describeContents(documents: readonly CandidateDocument[]): string {
  const byGroup = new Map<string, CandidateDocument[]>();
  for (const document of documents) {
    const group = groupOf(document);
    const bucket = byGroup.get(group);
    if (bucket) bucket.push(document);
    else byGroup.set(group, [document]);
  }

  const phrases = [...byGroup.entries()].map(([group, groupDocuments]) => {
    const years = new Set(
      groupDocuments
        .map((document) => document.financialYearLabel)
        .filter((label): label is string => label !== undefined),
    );
    const prose = groupProse(group as Parameters<typeof groupProse>[0]);
    return years.size > 1 ? `${numberWord(years.size)} years of ${prose}` : `the ${prose}`;
  });

  if (phrases.length <= 1) return phrases[0] ?? "the documents";
  return `${phrases.slice(0, -1).join(", ")} and ${phrases[phrases.length - 1] as string}`;
}

export interface BodyInput {
  readonly context: SubmissionContext;
  readonly recipient: BankerRecipient;
  readonly batch: AttachmentBatch;
  readonly batchCount: number;
  readonly sender: EmailSender;
}

/**
 * The whole email, as plain text.
 *
 * Plain text rather than HTML on purpose: it renders identically in every mail
 * client a branch uses, it cannot break, and it is what an employee writing
 * this by hand would send.
 *
 * The shape, and why each line is there:
 *
 *   Greeting              — named where we know the name.
 *   What is attached      — so the banker knows before opening anything.
 *   Which email this is   — only when there is more than one, because
 *                           "1 of 1" reads as machinery.
 *   The list              — every attachment by its full name, year included.
 *                           This is the line that ends "did you get the
 *                           FY 2023-24 return?" as a phone call.
 *   The ask               — one sentence, and it is the real one.
 *   Sign-off              — Amaze Loans and the mailbox that sent it.
 */
export function composeBody(input: BodyInput): string {
  const { context, recipient, batch, batchCount, sender } = input;

  const lines: string[] = [];

  lines.push(composeGreeting(recipient));
  lines.push("");

  const reference =
    context.caseNumber === undefined
      ? ""
      : ` Our reference is ${context.caseNumber}.`;

  lines.push(
    `Please find attached ${describeContents(batch.documents)} for ${context.customerName}'s ` +
      `${context.loanTypeName} application.${reference}`,
  );

  if (batchCount > 1) {
    lines.push("");
    lines.push(
      `This is email ${batch.sequence} of ${batchCount}. The file is over the attachment size ` +
        `a single email allows, so the documents are split across ${numberWord(batchCount)} emails ` +
        "sent together — nothing is missing.",
    );
  }

  lines.push("");
  lines.push(`Attached (${batch.documents.length}):`);
  for (const document of batch.documents) {
    lines.push(`  - ${document.label}`);
  }

  lines.push("");
  lines.push(
    "Please review the attached documents and let us know if anything further is required from our end.",
  );

  lines.push("");
  lines.push("Regards,");
  lines.push(sender.name);
  lines.push(sender.address);

  return lines.join("\n");
}

/**
 * A one-line summary of a whole submission, for the case timeline.
 *
 * "Documents sent to banker" rather than "Email sent" — the milestone asks for
 * exactly this, and it is the difference between a timeline somebody reads and
 * one they scroll past. `joinWithAmpersand` is reused so the timeline names the
 * same groups the subject did.
 */
export function describeSubmissionForTimeline(input: {
  readonly documentCount: number;
  readonly batchCount: number;
  readonly recipients: readonly string[];
  readonly counterparty?: string | undefined;
}): string {
  const documents = `${input.documentCount} verified document${input.documentCount === 1 ? "" : "s"}`;
  const emails = `${input.batchCount} email${input.batchCount === 1 ? "" : "s"}`;
  const to = joinWithAmpersand(input.recipients);
  const where = input.counterparty === undefined ? "" : ` at ${input.counterparty}`;
  return `Documents sent to banker${where} — ${documents} in ${emails} to ${to}`;
}
