-- ===========================================================================
-- 0008 — Permission catalog, role grants, and operational thresholds
--
-- GENERATED FILE. Do not edit by hand.
--
-- Produced by buildPermissionSeedSql() in src/domain/permissions/seed.ts from
-- the catalog in actions.ts, the grants in roles.ts, and the threshold keys in
-- settings/thresholds.ts. Those files are the single definition (ADR-022,
-- ADR-025); this migration is their projection into the database, which is
-- where RLS can read them.
--
-- To change a grant: edit roles.ts, run `npm run seed:permissions`, commit both.
-- seed.test.ts fails if this file and the catalog disagree.
-- ===========================================================================

-- Idempotent: re-running reconciles the database with the catalog rather than
-- appending to it. A grant removed from roles.ts must disappear here too, or
-- revoking a permission would require a hand-written migration — which is the
-- drift ADR-022 exists to prevent.

-- ---------------------------------------------------------------------------
-- permission — the catalog
-- ---------------------------------------------------------------------------

insert into permission (key, permission_group, level, description) values
  ('case.read', 'cases', 'row', 'See a case and everything that hangs off it.'),
  ('case.create', 'cases', 'row', 'Open a new case. A lead is a case (ADR-008), so this is the telecaller''s primary action. No row exists yet to scope against.'),
  ('case.update', 'cases', 'row', 'Change a case''s own fields and its party, property and requirement rows. Stage movement is not covered here — stages move through transitions.'),
  ('case.assign', 'cases', 'row', 'Change a case''s accountable owner (BR-011). Always an event.'),
  ('case.hold', 'cases', 'row', 'Place or lift a hold, with reason and follow-up date (ADR-021).'),
  ('case.mark_lost', 'cases', 'row', 'End a case as lost, with a reason from the controlled list (BR-013).'),
  ('case.reopen', 'cases', 'row', 'Return a lost case to the stage it was lost from.'),
  ('case.close', 'cases', 'row', 'Close a disbursed case. Closing asserts the invoice is raised, which is why it is Finance''s and not the owner''s.'),
  ('person.read', 'people-and-organisations', 'row', 'See a person and their identifiers, aliases and employment. Deliberately not narrowable: a telecaller must be able to discover that the caller is an existing customer, which is the product''s central promise (Principle #4).'),
  ('person.create', 'people-and-organisations', 'row', 'Record a new person. No row exists yet to scope against.'),
  ('person.update', 'people-and-organisations', 'row', 'Amend a person, their identifiers, aliases, employment, referrer profile and bank-contact relationships.'),
  ('person.merge', 'people-and-organisations', 'row', 'Merge two people into one, leaving the loser as a redirecting tombstone (BR-004). Reversible (BR-005), which is what makes restricting it tolerable.'),
  ('person.override_duplicate', 'people-and-organisations', 'row', 'Create a person the system believes is a duplicate. Requires a reason and writes an event (BR-053).'),
  ('organisation.read', 'people-and-organisations', 'row', 'See an organisation, its aliases, its lender profile and its bank contacts. Covers employers, borrowing firms, builders, banks and branches (ADR-014).'),
  ('organisation.create', 'people-and-organisations', 'row', 'Record a new organisation. Users never do this explicitly — typing a name resolves or creates one in the background (ADR-009).'),
  ('organisation.update', 'people-and-organisations', 'row', 'Amend an organisation, its aliases and its bank contacts. Found missing by the consistency audit — the catalog had create and merge but no update.'),
  ('organisation.merge', 'people-and-organisations', 'row', 'Merge two organisations, following the same tombstone-and-alias rules as people (BR-006). Near-matches are suggested, never auto-merged.'),
  ('property.read', 'people-and-organisations', 'row', 'See a property. Not narrowable for the same reason as person: one property appears across a purchase, a later top-up and a balance transfer, and recognising that is the point.'),
  ('property.create', 'people-and-organisations', 'row', 'Record a property. Duplicates are tolerated here — properties are found through their case and their people, which are well identified.'),
  ('property.update', 'people-and-organisations', 'row', 'Amend a property''s address, valuation and document numbers.'),
  ('property.merge', 'people-and-organisations', 'row', 'Merge two property records. Expected to be rare and requires an extra confirmation — wrongly linking two properties has a financial consequence far worse than a duplicate row (Identity Resolution Part 5).'),
  ('employment.read', 'people-and-organisations', 'row', 'See a person''s employment history. Employment type drives requirement generation, so the login desk needs it on every file.'),
  ('employment.record', 'people-and-organisations', 'row', 'Add or amend an employment relationship, including declared income. One permission rather than create plus update: an employment row is corrected far more often than a new one is genuinely added, and splitting them would mean every role that holds one holds the other.'),
  ('document.read', 'documents', 'row', 'See and download a document. Narrowable, unlike person: a document is the sensitive artefact, and `own` reaches it through the cases that reference it.'),
  ('document.upload', 'documents', 'row', 'Add a document, or a new version of one. Versions accumulate; nothing is overwritten in place (BR-031).'),
  ('document.verify', 'documents', 'row', 'Mark a document checked. Always attributed to a named human — the system never verifies (BR-032).'),
  ('document.delete_version', 'documents', 'row', 'Remove a document version. **Granted to nobody, deliberately.** Documents are versioned and never overwritten (BR-031), and a replaced document may be the one a bank already saw. Listed so the decision is explicit rather than accidental.'),
  ('requirement.waive', 'documents', 'row', 'Excuse a requirement, recording who, when and why (BR-035). A waiver sends an incomplete file to a bank; safety comes from attribution, not rarity.'),
  ('submission.read', 'banking', 'row', 'See a case''s submissions and their statuses — the grid that sits beneath the case stage and makes the two axes obvious (ADR-004).'),
  ('submission.create', 'banking', 'row', 'Send a file to a bank branch. A corrected file returning to the same branch is a new submission, never a reset of the old one (Workflow.md).'),
  ('submission.update_status', 'banking', 'row', 'Move a submission''s status, including recording a rejection with its standardised reason and the bank''s own wording (ADR-028).'),
  ('offer.read', 'banking', 'row', 'See what a bank came back with — amount, rate, tenure, conditions.'),
  ('offer.record', 'banking', 'row', 'Enter or revise an offer against a submission. A revision is a new offer row: comparing it against the original is the conversation with the customer.'),
  ('offer.accept', 'banking', 'row', 'Record that the customer accepted an offer. At most one per submission (BR-025); the unaccepted submissions then go to Withdrawn, not Rejected.'),
  ('task.read', 'work-and-communication', 'row', 'See tasks. At `own` this is the calling screen''s work list; at `all` it is how a manager sees what the team is carrying.'),
  ('task.create', 'work-and-communication', 'row', 'Raise a task for oneself. Assigning it to somebody else is `task.assign`, deliberately separate.'),
  ('task.update', 'work-and-communication', 'row', 'Amend or complete a task. Tasks are never deleted — a deleted task hides the fact that work was dropped (BR-041).'),
  ('task.assign', 'work-and-communication', 'row', 'Give a task to somebody else. Every task has exactly one assignee (BR-040).'),
  ('communication.read', 'work-and-communication', 'row', 'See logged calls, WhatsApp, email and meetings. Found missing by the audit — roles could log a communication but nothing said who could read one.'),
  ('communication.log', 'work-and-communication', 'row', 'Record an exchange with a person. Logged against both the person and the case, so a person''s full history is visible from their profile.'),
  ('note.read', 'work-and-communication', 'row', 'Read internal commentary on a case. Found missing by the audit.'),
  ('note.create', 'work-and-communication', 'row', 'Write internal commentary, immutable after a short edit window. Notes are not a place for structured facts — if something is written repeatedly, it wants a field (Principle #11).'),
  ('identifier.view_full', 'sensitive', 'column', 'See an unmasked identifier value — full PAN rather than `ABCxxxxx1F`. Column-level: the person row is visible either way (ADR-026). The only permission whose denial is itself an event, because revealing one value is a per-record disclosure decision rather than a whole-surface one.'),
  ('commercial.view', 'sensitive', 'column', 'See money the customer never sees: commission terms, referrer payouts, login fees, invoice figures. Column-level (ADR-026) — the case, submission and referrer rows are visible without it.'),
  ('event.view', 'sensitive', 'row', 'Read the audit log. Row-level rather than column-level: an event is either yours to see or it is not.'),
  ('user.read', 'administration', 'row', 'See who holds an account and which roles they hold. Held at `all` by every role: colleagues'' names appear on every case, and `own` alone would make a case owner unrenderable.'),
  ('user.manage', 'administration', 'row', 'Create and deactivate accounts. Never delete — a departed employee''s name must survive on every case they touched (BR-062).'),
  ('role.assign', 'administration', 'row', 'Grant and revoke roles. Assignment is runtime data, never a migration (ADR-022).'),
  ('master_data.read', 'administration', 'row', 'Read reference tables — loan products, bank products, document types, rejection reasons, operational thresholds, the permission catalog itself. Held by every role. It exists so that no table is bound to a null permission: ''everyone may read this'' is a decision and should be written down as one (ADR-027).'),
  ('master_data.manage', 'administration', 'row', 'Maintain reference tables — add a bank, a branch, a bank product, a document type, a rejection reason. Not a licence to alter operational records.'),
  ('report.view', 'administration', 'row', 'Read aggregate reporting. Aggregates are computed over rows the user may see.')
on conflict (key) do update set
  permission_group = excluded.permission_group,
  level            = excluded.level,
  description      = excluded.description;

-- ---------------------------------------------------------------------------
-- role_permission — who holds what, at which scope
--
-- Grants are reconciled BEFORE stale permissions are removed. role_permission
-- carries a foreign key to permission, so deleting a withdrawn permission
-- while a grant still references it would fail the migration — and a seed that
-- only works on an empty database is not a seed.
-- ---------------------------------------------------------------------------

insert into role_permission (role, permission, scope) values
  ('telecaller', 'case.read', 'own'),
  ('telecaller', 'case.create', 'all'),
  ('telecaller', 'case.update', 'own'),
  ('telecaller', 'case.hold', 'own'),
  ('telecaller', 'case.mark_lost', 'own'),
  ('telecaller', 'case.reopen', 'own'),
  ('telecaller', 'person.read', 'all'),
  ('telecaller', 'person.create', 'all'),
  ('telecaller', 'person.update', 'all'),
  ('telecaller', 'organisation.read', 'all'),
  ('telecaller', 'organisation.create', 'all'),
  ('telecaller', 'organisation.update', 'all'),
  ('telecaller', 'property.read', 'all'),
  ('telecaller', 'employment.read', 'all'),
  ('telecaller', 'employment.record', 'all'),
  ('telecaller', 'document.read', 'own'),
  ('telecaller', 'document.upload', 'own'),
  ('telecaller', 'submission.read', 'own'),
  ('telecaller', 'offer.read', 'own'),
  ('telecaller', 'task.read', 'own'),
  ('telecaller', 'task.create', 'own'),
  ('telecaller', 'task.update', 'own'),
  ('telecaller', 'communication.read', 'own'),
  ('telecaller', 'communication.log', 'own'),
  ('telecaller', 'note.read', 'own'),
  ('telecaller', 'note.create', 'own'),
  ('telecaller', 'user.read', 'all'),
  ('telecaller', 'master_data.read', 'all'),
  ('login_executive', 'case.read', 'all'),
  ('login_executive', 'case.create', 'all'),
  ('login_executive', 'case.update', 'all'),
  ('login_executive', 'case.hold', 'own'),
  ('login_executive', 'case.mark_lost', 'own'),
  ('login_executive', 'case.reopen', 'own'),
  ('login_executive', 'person.read', 'all'),
  ('login_executive', 'person.create', 'all'),
  ('login_executive', 'person.update', 'all'),
  ('login_executive', 'organisation.read', 'all'),
  ('login_executive', 'organisation.create', 'all'),
  ('login_executive', 'organisation.update', 'all'),
  ('login_executive', 'property.read', 'all'),
  ('login_executive', 'property.create', 'all'),
  ('login_executive', 'property.update', 'all'),
  ('login_executive', 'employment.read', 'all'),
  ('login_executive', 'employment.record', 'all'),
  ('login_executive', 'document.read', 'all'),
  ('login_executive', 'document.upload', 'all'),
  ('login_executive', 'document.verify', 'all'),
  ('login_executive', 'requirement.waive', 'all'),
  ('login_executive', 'submission.read', 'all'),
  ('login_executive', 'submission.create', 'all'),
  ('login_executive', 'submission.update_status', 'all'),
  ('login_executive', 'offer.read', 'all'),
  ('login_executive', 'offer.record', 'all'),
  ('login_executive', 'offer.accept', 'all'),
  ('login_executive', 'task.read', 'own'),
  ('login_executive', 'task.create', 'own'),
  ('login_executive', 'task.update', 'own'),
  ('login_executive', 'communication.read', 'all'),
  ('login_executive', 'communication.log', 'all'),
  ('login_executive', 'note.read', 'all'),
  ('login_executive', 'note.create', 'all'),
  ('login_executive', 'identifier.view_full', 'all'),
  ('login_executive', 'user.read', 'all'),
  ('login_executive', 'master_data.read', 'all'),
  ('manager', 'case.read', 'all'),
  ('manager', 'case.create', 'all'),
  ('manager', 'case.update', 'all'),
  ('manager', 'case.assign', 'all'),
  ('manager', 'case.hold', 'all'),
  ('manager', 'case.mark_lost', 'all'),
  ('manager', 'case.reopen', 'all'),
  ('manager', 'person.read', 'all'),
  ('manager', 'person.create', 'all'),
  ('manager', 'person.update', 'all'),
  ('manager', 'person.merge', 'all'),
  ('manager', 'person.override_duplicate', 'all'),
  ('manager', 'organisation.read', 'all'),
  ('manager', 'organisation.create', 'all'),
  ('manager', 'organisation.update', 'all'),
  ('manager', 'organisation.merge', 'all'),
  ('manager', 'property.read', 'all'),
  ('manager', 'property.create', 'all'),
  ('manager', 'property.update', 'all'),
  ('manager', 'property.merge', 'all'),
  ('manager', 'employment.read', 'all'),
  ('manager', 'employment.record', 'all'),
  ('manager', 'document.read', 'all'),
  ('manager', 'document.upload', 'all'),
  ('manager', 'document.verify', 'all'),
  ('manager', 'requirement.waive', 'all'),
  ('manager', 'submission.read', 'all'),
  ('manager', 'submission.create', 'all'),
  ('manager', 'submission.update_status', 'all'),
  ('manager', 'offer.read', 'all'),
  ('manager', 'offer.record', 'all'),
  ('manager', 'offer.accept', 'all'),
  ('manager', 'task.read', 'all'),
  ('manager', 'task.create', 'all'),
  ('manager', 'task.update', 'all'),
  ('manager', 'task.assign', 'all'),
  ('manager', 'communication.read', 'all'),
  ('manager', 'communication.log', 'all'),
  ('manager', 'note.read', 'all'),
  ('manager', 'note.create', 'all'),
  ('manager', 'identifier.view_full', 'all'),
  ('manager', 'event.view', 'all'),
  ('manager', 'user.read', 'all'),
  ('manager', 'master_data.read', 'all'),
  ('manager', 'report.view', 'all'),
  ('finance', 'case.read', 'all'),
  ('finance', 'case.close', 'all'),
  ('finance', 'person.read', 'all'),
  ('finance', 'organisation.read', 'all'),
  ('finance', 'submission.read', 'all'),
  ('finance', 'offer.read', 'all'),
  ('finance', 'commercial.view', 'all'),
  ('finance', 'user.read', 'all'),
  ('finance', 'master_data.read', 'all'),
  ('finance', 'report.view', 'all'),
  ('admin', 'case.read', 'all'),
  ('admin', 'person.read', 'all'),
  ('admin', 'organisation.read', 'all'),
  ('admin', 'property.read', 'all'),
  ('admin', 'employment.read', 'all'),
  ('admin', 'submission.read', 'all'),
  ('admin', 'offer.read', 'all'),
  ('admin', 'task.read', 'all'),
  ('admin', 'event.view', 'all'),
  ('admin', 'user.read', 'all'),
  ('admin', 'user.manage', 'all'),
  ('admin', 'role.assign', 'all'),
  ('admin', 'master_data.read', 'all'),
  ('admin', 'master_data.manage', 'all'),
  ('admin', 'report.view', 'all')
on conflict (role, permission) do update set
  scope = excluded.scope;

delete from role_permission
 where (role, permission) not in (
       ('telecaller', 'case.read'),
       ('telecaller', 'case.create'),
       ('telecaller', 'case.update'),
       ('telecaller', 'case.hold'),
       ('telecaller', 'case.mark_lost'),
       ('telecaller', 'case.reopen'),
       ('telecaller', 'person.read'),
       ('telecaller', 'person.create'),
       ('telecaller', 'person.update'),
       ('telecaller', 'organisation.read'),
       ('telecaller', 'organisation.create'),
       ('telecaller', 'organisation.update'),
       ('telecaller', 'property.read'),
       ('telecaller', 'employment.read'),
       ('telecaller', 'employment.record'),
       ('telecaller', 'document.read'),
       ('telecaller', 'document.upload'),
       ('telecaller', 'submission.read'),
       ('telecaller', 'offer.read'),
       ('telecaller', 'task.read'),
       ('telecaller', 'task.create'),
       ('telecaller', 'task.update'),
       ('telecaller', 'communication.read'),
       ('telecaller', 'communication.log'),
       ('telecaller', 'note.read'),
       ('telecaller', 'note.create'),
       ('telecaller', 'user.read'),
       ('telecaller', 'master_data.read'),
       ('login_executive', 'case.read'),
       ('login_executive', 'case.create'),
       ('login_executive', 'case.update'),
       ('login_executive', 'case.hold'),
       ('login_executive', 'case.mark_lost'),
       ('login_executive', 'case.reopen'),
       ('login_executive', 'person.read'),
       ('login_executive', 'person.create'),
       ('login_executive', 'person.update'),
       ('login_executive', 'organisation.read'),
       ('login_executive', 'organisation.create'),
       ('login_executive', 'organisation.update'),
       ('login_executive', 'property.read'),
       ('login_executive', 'property.create'),
       ('login_executive', 'property.update'),
       ('login_executive', 'employment.read'),
       ('login_executive', 'employment.record'),
       ('login_executive', 'document.read'),
       ('login_executive', 'document.upload'),
       ('login_executive', 'document.verify'),
       ('login_executive', 'requirement.waive'),
       ('login_executive', 'submission.read'),
       ('login_executive', 'submission.create'),
       ('login_executive', 'submission.update_status'),
       ('login_executive', 'offer.read'),
       ('login_executive', 'offer.record'),
       ('login_executive', 'offer.accept'),
       ('login_executive', 'task.read'),
       ('login_executive', 'task.create'),
       ('login_executive', 'task.update'),
       ('login_executive', 'communication.read'),
       ('login_executive', 'communication.log'),
       ('login_executive', 'note.read'),
       ('login_executive', 'note.create'),
       ('login_executive', 'identifier.view_full'),
       ('login_executive', 'user.read'),
       ('login_executive', 'master_data.read'),
       ('manager', 'case.read'),
       ('manager', 'case.create'),
       ('manager', 'case.update'),
       ('manager', 'case.assign'),
       ('manager', 'case.hold'),
       ('manager', 'case.mark_lost'),
       ('manager', 'case.reopen'),
       ('manager', 'person.read'),
       ('manager', 'person.create'),
       ('manager', 'person.update'),
       ('manager', 'person.merge'),
       ('manager', 'person.override_duplicate'),
       ('manager', 'organisation.read'),
       ('manager', 'organisation.create'),
       ('manager', 'organisation.update'),
       ('manager', 'organisation.merge'),
       ('manager', 'property.read'),
       ('manager', 'property.create'),
       ('manager', 'property.update'),
       ('manager', 'property.merge'),
       ('manager', 'employment.read'),
       ('manager', 'employment.record'),
       ('manager', 'document.read'),
       ('manager', 'document.upload'),
       ('manager', 'document.verify'),
       ('manager', 'requirement.waive'),
       ('manager', 'submission.read'),
       ('manager', 'submission.create'),
       ('manager', 'submission.update_status'),
       ('manager', 'offer.read'),
       ('manager', 'offer.record'),
       ('manager', 'offer.accept'),
       ('manager', 'task.read'),
       ('manager', 'task.create'),
       ('manager', 'task.update'),
       ('manager', 'task.assign'),
       ('manager', 'communication.read'),
       ('manager', 'communication.log'),
       ('manager', 'note.read'),
       ('manager', 'note.create'),
       ('manager', 'identifier.view_full'),
       ('manager', 'event.view'),
       ('manager', 'user.read'),
       ('manager', 'master_data.read'),
       ('manager', 'report.view'),
       ('finance', 'case.read'),
       ('finance', 'case.close'),
       ('finance', 'person.read'),
       ('finance', 'organisation.read'),
       ('finance', 'submission.read'),
       ('finance', 'offer.read'),
       ('finance', 'commercial.view'),
       ('finance', 'user.read'),
       ('finance', 'master_data.read'),
       ('finance', 'report.view'),
       ('admin', 'case.read'),
       ('admin', 'person.read'),
       ('admin', 'organisation.read'),
       ('admin', 'property.read'),
       ('admin', 'employment.read'),
       ('admin', 'submission.read'),
       ('admin', 'offer.read'),
       ('admin', 'task.read'),
       ('admin', 'event.view'),
       ('admin', 'user.read'),
       ('admin', 'user.manage'),
       ('admin', 'role.assign'),
       ('admin', 'master_data.read'),
       ('admin', 'master_data.manage'),
       ('admin', 'report.view')
     );

-- Now the withdrawn permissions themselves, with no grants left pointing at
-- them.
delete from permission
 where key not in (
       'case.read',
       'case.create',
       'case.update',
       'case.assign',
       'case.hold',
       'case.mark_lost',
       'case.reopen',
       'case.close',
       'person.read',
       'person.create',
       'person.update',
       'person.merge',
       'person.override_duplicate',
       'organisation.read',
       'organisation.create',
       'organisation.update',
       'organisation.merge',
       'property.read',
       'property.create',
       'property.update',
       'property.merge',
       'employment.read',
       'employment.record',
       'document.read',
       'document.upload',
       'document.verify',
       'document.delete_version',
       'requirement.waive',
       'submission.read',
       'submission.create',
       'submission.update_status',
       'offer.read',
       'offer.record',
       'offer.accept',
       'task.read',
       'task.create',
       'task.update',
       'task.assign',
       'communication.read',
       'communication.log',
       'note.read',
       'note.create',
       'identifier.view_full',
       'commercial.view',
       'event.view',
       'user.read',
       'user.manage',
       'role.assign',
       'master_data.read',
       'master_data.manage',
       'report.view'
     );

-- ---------------------------------------------------------------------------
-- operational_threshold — keys are code, values are data (ADR-025)
--
-- The insert is deliberately NOT an upsert of the value: a threshold someone
-- tuned in production must survive a redeploy. Only the key set is reconciled.
-- ---------------------------------------------------------------------------

insert into operational_threshold (key, value_days, description) values
  ('idle_days.new', 1, 'Days a case may sit in "new" before its health degrades.'),
  ('idle_days.contacted', 3, 'Days a case may sit in "contacted" before its health degrades.'),
  ('idle_days.appointment_fixed', 2, 'Days a case may sit in "appointment fixed" before its health degrades.'),
  ('idle_days.documents_pending', 5, 'Days a case may sit in "documents pending" before its health degrades.'),
  ('idle_days.ready_for_submission', 2, 'Days a case may sit in "ready for submission" before its health degrades.'),
  ('idle_days.submitted', 10, 'Days a case may sit in "submitted" before its health degrades.'),
  ('idle_days.sanctioned', 7, 'Days a case may sit in "sanctioned" before its health degrades.'),
  ('idle_days.disbursed', 14, 'Days a case may sit in "disbursed" before its health degrades.'),
  ('offer_expiry_warning_days', 7, 'Days before an offer expires at which a task is raised to the case owner.'),
  ('unverified_document_age_days', 3, 'Days a document may sit received-but-unverified before case health degrades.'),
  ('default_hold_follow_up_days', 14, 'Default follow-up date offered when a case is put on hold.')
on conflict (key) do nothing;

delete from operational_threshold
 where key not in (
       'idle_days.new',
       'idle_days.contacted',
       'idle_days.appointment_fixed',
       'idle_days.documents_pending',
       'idle_days.ready_for_submission',
       'idle_days.submitted',
       'idle_days.sanctioned',
       'idle_days.disbursed',
       'offer_expiry_warning_days',
       'unverified_document_age_days',
       'default_hold_follow_up_days'
     );
